FS_TARGET = 96000
MAX_SECONDS = 10

WEIGHT_LEN_SPEECH = 10
MU_ENHANCE = 0.0005
MU_FXLMS = 0.08

INPUT_SNR_DB = 0
ALPHA_SPEECH_LEAKAGE = 0.0

WAV_FILENAME = "harvard.wav"
WAV_NOISE = 'noise_airplane.wav'
NOISE_INPUT = True